name: kubectl
author: Myrotvorets
description: kubectl as a GitHub Action
runs:
  using: docker
  image: Dockerfile
  post-entrypoint: /usr/local/bin/cleanup.sh
branding:
  icon: terminal
  color: blue
